### ORDER
GET http://localhost:8080/orders

### ORDER
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 270,
      "quantity": 3
    },
    {
      "bookId": 231,
      "quantity": 3
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

###
GET http://localhost:8080/orders/9

###
GET http://localhost:8080/orders

###
PUT http://localhost:8080/orders/21/status
Content-Type: application/json

{
  "status": "CANCELED"
}
