version: '3.1'

services:
  db:
    container_name: bookarodb
    image: postgres:12.9
    restart: always
    environment:
      POSTGRES_DB: bookaro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432


# docker-compose up -d
# docker-compose down
# docker ps